// all api endpoint goes here
export const API_ENDPOINTS = {
  TOURS: "/tours",
  TOUR_SERVICES: "/tour-services",
  DEPARTURES_PRICING: "/departures-pricing",
  INDIVIDUAL_PRICING: "/individual-pricing",
  TOUR_ROUTES: "/routes",
  REVIEWS: "/reviews",
  NEW_REVIEWS: "/reviews/create",
  TOURTYPE: "/tour-type",
  CAR_WITHOUT_DRIVER: "/without-driver",
  CAR_WITH_DRIVER: "/with-driver",
  AIRPORT_TRANSPORT: "/airport-transport",
  HOTELS: "/hotels",
  HOTELTYPE: "/hotel-type",
  FILEUPLOADS: "/file/upload",
  TOUR_ACCESSORIES: "/tour-accessories",
  ACCESSORY_TYPE: "/accessory-type",
  RIDE_PLAN: "/ride-plan",
  NEW_RIDE_PLAN: "/ride-plan/create",
  CALLBACK: "/call-back",
  THING_TO_SEE: "/thing-to-see",
  THING_TO_DO: "/thing-to-do",
  FOOD_AND_DRINKS: "/food-and-drinks",
  DESTINATION: "/destinations",
  IMAGES: "/images",
  ACCESSORY_PRICING: "/accessories-pricing",
  MAIL_REQUEST: "/mail",
  MICE: "/mice",
  CURRENCY: "/currency",
  STATIC_PAGES: "/static-pages",
  SURROUNDING: "/surrounding",
  EVENTS: "/events",
  BLOGS: "/blogs",
  RUBRICS: "/rubrics",
  VACANCY: "/vacancy"
};
